
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-7pm-2
owner: ucsb-cs156-w24
repo_name: team02-w24-7pm-2
pull_requests: [{"author":{"id":"U_kgDOBXc-yA","is_bot":false,"login":"nguyenliliana","name":""},"headRefName":"Liliana-MenuItemReviewController","number":53,"title":"LN-  MenuItemReview Controller & Tests for ALL and POST methods","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/53"},{"author":{"id":"MDQ6VXNlcjE1ODMzOTY4","is_bot":false,"login":"ashton-wong","name":"Ashton Wong"},"headRefName":"aw-UCSBDiningCommonsMenuItem-create-db","number":52,"title":"AW - Database Setup","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/52"},{"author":{"id":"MDQ6VXNlcjUzMTg4OTY4","is_bot":false,"login":"elaineeeho","name":"Elaine Ho"},"headRefName":"eh-UCSBOrganization-DELETE-endpoint","number":49,"title":"EH - Implemented DELETE endpoint","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/49"},{"author":{"id":"MDQ6VXNlcjUzMTg4OTY4","is_bot":false,"login":"elaineeeho","name":"Elaine Ho"},"headRefName":"eh-UCSBOrganization-PUT-endpoint","number":48,"title":"EH - Implemented PUT endpoint ","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/48"},{"author":{"id":"MDQ6VXNlcjUzMTg4OTY4","is_bot":false,"login":"elaineeeho","name":"Elaine Ho"},"headRefName":"eh-UCSBOrganization-GET-endpoint","number":47,"title":"EH - UCSBOrganization GET endpoint","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/47"},{"author":{"id":"MDQ6VXNlcjUzMTg4OTY4","is_bot":false,"login":"elaineeeho","name":"Elaine Ho"},"headRefName":"eh-UCSBOrganization-create-controller","number":46,"title":"EH - Create UCSBOrganizationController and tests","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/46"},{"author":{"id":"U_kgDOBXc-yA","is_bot":false,"login":"nguyenliliana","name":""},"headRefName":"Liliana-MenuItemReviewTable","number":44,"title":"Liliana menu item review table","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/44"}]
