
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-7pm-2
owner: ucsb-cs156-w24
repo_name: team02-w24-7pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjMyMzQ1NzI0","is_bot":false,"login":"Kavya75","name":"Kavya Verma"},"headRefName":"Kavya-HelpRequest-GET","number":61,"title":"Kavya - HelpRequest GET Endpoint","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/61"},{"author":{"id":"MDQ6VXNlcjE1ODMzOTY4","is_bot":false,"login":"ashton-wong","name":"Ashton Wong"},"headRefName":"aw-UCSBDiningCommonsMenuItem-create-controller","number":60,"title":"AW - Create Dining Commons Menu Item Controller and Tests","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/60"},{"author":{"id":"MDQ6VXNlcjMyMzQ1NzI0","is_bot":false,"login":"Kavya75","name":"Kavya Verma"},"headRefName":"Kavya-HelpRequestController","number":59,"title":"Kavya - Add HelpRequestController and HelpRequestControllerTests","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/59"},{"author":{"id":"MDQ6VXNlcjc3NDczMTE0","is_bot":false,"login":"andy-gale","name":"Andy Gale"},"headRefName":"Andy-ReqRequestController","number":58,"title":"Andy-  recommendationrequest controller GET and POST","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/58"},{"author":{"id":"MDQ6VXNlcjc3NDczMTE0","is_bot":false,"login":"andy-gale","name":"Andy Gale"},"headRefName":"Andy-ReqRequestTable","number":57,"title":"AG - Create database table for RecommendationRequest","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/57"},{"author":{"id":"MDQ6VXNlcjE1ODMzOTY4","is_bot":false,"login":"ashton-wong","name":"Ashton Wong"},"headRefName":"aw-UCSBDiningCommonsMenuItem-create-db","number":52,"title":"AW - Database Setup","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/52"}]
