
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-7pm-2
owner: ucsb-cs156-w24
repo_name: team02-w24-7pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjE1ODMzOTY4","is_bot":false,"login":"ashton-wong","name":"Ashton Wong"},"headRefName":"aw-UCSBDiningCommonsMenuItem-DELETE-endpoint","number":67,"title":"AW - Add DELETE Endpoint for Menu Items","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/67"},{"author":{"id":"MDQ6VXNlcjE1ODMzOTY4","is_bot":false,"login":"ashton-wong","name":"Ashton Wong"},"headRefName":"aw-UCSBDiningCommonsMenuItem-PUT-endpoint","number":66,"title":"AW - Add PUT Endpoint for Menu Items","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/66"},{"author":{"id":"MDQ6VXNlcjMyMzQ1NzI0","is_bot":false,"login":"Kavya75","name":"Kavya Verma"},"headRefName":"Kavya-HelpRequest-DELETE","number":65,"title":"Kavya - Help Request DELETE","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/65"},{"author":{"id":"U_kgDOBdC7MQ","is_bot":false,"login":"michaelw1985","name":"Michael W"},"headRefName":"Michael-ArticlesTable","number":64,"title":"Michael articles table","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/64"},{"author":{"id":"MDQ6VXNlcjE1ODMzOTY4","is_bot":false,"login":"ashton-wong","name":"Ashton Wong"},"headRefName":"aw-UCSBDiningCommonsMenuItem-GET-endpoint","number":63,"title":"AW - Added the GET endpoint to the Menu Item Controller","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/63"},{"author":{"id":"MDQ6VXNlcjMyMzQ1NzI0","is_bot":false,"login":"Kavya75","name":"Kavya Verma"},"headRefName":"Kavya-HelpRequest-PUT","number":62,"title":"Kavya - HelpRequest PUT Endpoint","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/62"},{"author":{"id":"MDQ6VXNlcjMyMzQ1NzI0","is_bot":false,"login":"Kavya75","name":"Kavya Verma"},"headRefName":"Kavya-HelpRequest-GET","number":61,"title":"Kavya - HelpRequest GET Endpoint","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/61"},{"author":{"id":"MDQ6VXNlcjMyMzQ1NzI0","is_bot":false,"login":"Kavya75","name":"Kavya Verma"},"headRefName":"Kavya-HelpRequestController","number":59,"title":"Kavya - Add HelpRequestController and HelpRequestControllerTests","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/59"}]
