
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-7pm-2
owner: ucsb-cs156-w24
repo_name: team02-w24-7pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjc3NDczMTE0","is_bot":false,"login":"andy-gale","name":"Andy Gale"},"headRefName":"Andy-RecommendationRequest-Delete","number":76,"title":"Andy recommendation request delete","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/76"},{"author":{"id":"MDQ6VXNlcjc3NDczMTE0","is_bot":false,"login":"andy-gale","name":"Andy Gale"},"headRefName":"Andy-RecommendationRequest-Put","number":75,"title":"Andy recommendation request put","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/75"},{"author":{"id":"MDQ6VXNlcjc3NDczMTE0","is_bot":false,"login":"andy-gale","name":"Andy Gale"},"headRefName":"Andy-RecommendationRequest-Show","number":74,"title":"Andy recommendation request show","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/74"},{"author":{"id":"MDQ6VXNlcjc3NDczMTE0","is_bot":false,"login":"andy-gale","name":"Andy Gale"},"headRefName":"Andy-RecommendationRequestController","number":72,"title":"Andy recommendation request controller","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/72"},{"author":{"id":"MDQ6VXNlcjc3NDczMTE0","is_bot":false,"login":"andy-gale","name":"Andy Gale"},"headRefName":"Andy-ReqRequestTable","number":71,"title":"Andy req request table","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/71"},{"author":{"id":"U_kgDOBdC7MQ","is_bot":false,"login":"michaelw1985","name":"Michael W"},"headRefName":"Michael-ArticlesTable","number":64,"title":"Michael articles table","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/64"}]
