
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-7pm-2
owner: ucsb-cs156-w24
repo_name: team02-w24-7pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjc3NDczMTE0","is_bot":false,"login":"andy-gale","name":"Andy Gale"},"headRefName":"Andy-ReqRequestTable","number":57,"title":"AG - Create database table for RecommendationRequest","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/57"},{"author":{"id":"U_kgDOBXc-yA","is_bot":false,"login":"nguyenliliana","name":""},"headRefName":"Liliana-MenuItemReview-DELETE","number":56,"title":"LN - Implemented DELETE endpoint for MenuItemReview","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/56"},{"author":{"id":"U_kgDOBXc-yA","is_bot":false,"login":"nguyenliliana","name":""},"headRefName":"Liliana-MenuItemReview-PUT","number":55,"title":"LN - Implemented PUT endpoint for MenuItemReview","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/55"},{"author":{"id":"U_kgDOBXc-yA","is_bot":false,"login":"nguyenliliana","name":""},"headRefName":"Liliana-MenuItemReview-GET","number":54,"title":"LN - Implemented GET endpoint for MenuItemReview","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/54"},{"author":{"id":"U_kgDOBXc-yA","is_bot":false,"login":"nguyenliliana","name":""},"headRefName":"Liliana-MenuItemReviewController","number":53,"title":"LN-  MenuItemReview Controller & Tests for ALL and POST methods","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/53"},{"author":{"id":"MDQ6VXNlcjE1ODMzOTY4","is_bot":false,"login":"ashton-wong","name":"Ashton Wong"},"headRefName":"aw-UCSBDiningCommonsMenuItem-create-db","number":52,"title":"AW - Database Setup","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/52"},{"author":{"id":"U_kgDOBXc-yA","is_bot":false,"login":"nguyenliliana","name":""},"headRefName":"Liliana-MenuItemReviewTable","number":44,"title":"Liliana menu item review table","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-2/pull/44"}]
